tasks:
  - name: App
    init: npm install
    command: npm run start
    openMode: split-left

  - name: Test
    command: npm run test
    openMode: split-right

  - name: Set up email
    command: |
      clear
      printf "\n\n\n"
      printf "\u001b[36;1mAutofilling Email\u001b[0m\n"
      printf "\u001b[2;1mEach exercise comes with a elaboration form to help your retention. Providing your email now will mean you don't have to provide it each time you fill out the form.\u001b[0m\n"

      npx "https://gist.github.com/kentcdodds/2d44448a8997b9964b1be44cd294d1f5" \
        && exit 0

vscode:
  extensions:
    - VisualStudioExptTeam.vscodeintellicode
    - dbaeumer.vscode-eslint
    - formulahendry.auto-rename-tag
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
