name: deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  setup:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 26

      - name: ▶️ Add repo
        run: |
          npx --yes epicshop@latest add ${{ github.event.repository.name }}#${{ github.head_ref || github.ref_name }} ./workshop
        env:
          # Kept getting npm ECOMPROMISED errors on windows. This fixed it.
          npm_config_cache: ${{ runner.temp }}/npm-cache
          SKIP_PLAYWRIGHT: true

      - name: ʦ TypeScript
        run: npm run typecheck
        working-directory: ./workshop

      - name: ⬣ ESLint
        run: npm run lint
        working-directory: ./workshop

      # TODO: get this working again
      # - name: ⬇️ Install Playwright
      #   run: npm --prefix epicshop run test:setup

      # - name: 🧪 In-browser tests
      #   run: npm --prefix epicshop test

  deploy:
    name: 🚀 Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # only deploy main branch on pushes
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: 🚀 Deploy
        run: flyctl deploy --remote-only
        working-directory: ./epicshop
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
